### ISSUE TITLE
New BMDB data not appearing in portal

### ISSUE THREAD

**Issue by mryan4** [EDRN/P5#133]
## 🐛 Data that I entered into BMDB last week has not appeared in the portal yet.  Is the ingest working?

Put a clear and concise description of what the bug is here. 

## 📜 How To Reproduce

Looks like the ingest stopped working on 7/16.  Some biomarkers curated on that day appear in the portal with all their data, and some do not.

APOB AND APOC3 were curated on 7/16, and their aliases, publication, and resources DO appear.

APOH was curated on 7/16 as well, and for this biomarker all biomarkers curated after, the aliases, publication, and resources are not in the public portal. 

(I am currently adding aliases, publication, and resources to the Paulovich biomarkers that I already added to the BMDB a few weeks ago.)

Thanks!

**Comment by nutjob4life** [comment]
Ingest started on 7-23 but the Amazon EC2 instance which runs the portal shutdown and restarted, leaving the ingest in an unfinished state. When ingest started again the next day, it saw it was in-progress from the night before. I've reset the ingest and re-done it manually.

Note this biomarker: https://edrn.nci.nih.gov/data-and-resources/biomarkers/apoh … it has all its aliases.

However, it looks like doing a full-ingest may exceed some limits on the EC2 which causes the restart? It may be necessary to do just part of the ingest at a time, perhaps these steps:

1. archive/resources/body-systems, archive/resources/diseases, archive/resources/miscellaneous-resources
2. data-and-resources/publications
3. about/mission-and-structure/sites
4. data-and-resources/protocols
5. data-and-resources/data
6. data-and-resources/biomarkers
7. about/mission-and-structure/groups

The issue is that we'd have to fake some Plone form submissions to change that order which is kind of gross. Another alternative is to boost the resources on the EC2.
