### ISSUE TITLE
Filter/Search Publications by Year

### ISSUE THREAD

**Issue by askarlupka** [EDRN/P5#162]
## 🤔 Tell Us About the Feature

I would like to filter the publications by year. I specifically was looking for a publications in 2021. When searching by '2021' in the general search term box I received no results. Further, I attempted to sort the list of publications by year to make it easier to navigate that way but there was no sort feature.

## 🎇 What Solution You'd Like

Preferably I want to select a bar in the chart and have it automatically filter to that selected year.

## 〽️ Alternative Ideas

Another alternative would be to have a search/filter category that allows for the year to be selected on.

## 🗺 Context

![image](https://user-images.githubusercontent.com/54122306/192582434-5a73d407-bfdf-49ce-b58a-edf9a4386551.png)

After  Searching:

![image](https://user-images.githubusercontent.com/54122306/192582608-fd25e310-0114-4298-8b63-9a488fa620bf.png)

**Comment by nutjob4life** [comment]
Thanks for the submission @askarlupka! 

Yeah, this has definitely been a problem with the portal going back to version 4.1 and it's still not fixed in 5.1.4. However in 6.0.0 it is finally addressed, and includes not just search by year, but sorting by year as well as exporting the results table (with your preferred search setup) as an Excel file, PDF, CSV, or even just copy to your clipboard.
