### ISSUE TITLE
Updates to Protocol Page

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#190]
on the Protocol Page - https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/protocols/

The graphs that are shown on the Protocols page: Fields of Research, Collaborative Groups and Diseases Studied. 
Dan would like to add Diseases Studied to the table below the graphs, if that doesn't make the table too crowded.

The Collaborative Group Breast should be Breast/GYN

Can you add the hover over the graphs back?

**Comment by nutjob4life** [comment]
@hoodriverheather, here are my responses, in reverse order:

-  Hover is back.
- Collaborative group is now "Breast/Gyn"
- Adding a "Diseases Studied" column to the table makes it feel a little cramped. I have to expand to 1400 pixels wide (the max considered usable):

<img width="1346" alt="Screenshot 2022-12-20 at 10 59 58 AM" src="https://user-images.githubusercontent.com/814813/208723517-00373c13-3e42-4c8b-9e04-7168f086425d.png">

(The other columns cannot be shrunk because they have drop-down menus in their headers and footers.)

Part of the issue is that protocols can study multiple diseases. Another part of the problem is that so many of the diseases have these _really long, redundant_ names:

- Liver cell carcinoma
- Lymphoid leukaemia
- Malignant melanoma of skin
- Malignant neoplasm of bladder
- Malignant neoplasm of bone and articular cartilage
- Malignant neoplasm of brain
- Malignant neoplasm of breast
- Malignant neoplasm of bronchus and lung
- Malignant neoplasm of cervix uteri
- Malignant neoplasm of colon
- Malignant neoplasm of esophagus
- Malignant neoplasm of hypopharynx
- Malignant neoplasm of kidney
- Malignant neoplasm of larynx
- Malignant neoplasm of nasal cavities middle ear and accessory sinuses
- Malignant neoplasm of nasopharynx
- Malignant neoplasm of oropharynx
- Malignant neoplasm of other and unspecified parts of mouth
- Malignant neoplasm of ovary
- Malignant neoplasm of pancreas
- Malignant neoplasm of prostate
- Malignant neoplasm of rectum
- Malignant neoplasm of stomach
- Malignant neoplasm of testis
- Malignant neoplasm of thyroid gland
- Malignant neoplasm of uterus
- Malignant neoplasm of vagina
- Malignant neoplasms of lip, oral cavity and pharynx
- Myeloid leukaemia
- Plasma cell leukaemia

All that extra "malignant neoplasm of" crowds things. Are we allowed to abbreviate?

Also, I mentioned I can't shrink the other columns because they have drop-down menus. The "Diseases Studied" does not:

<img width="1315" alt="Screenshot 2022-12-20 at 11 01 58 AM" src="https://user-images.githubusercontent.com/814813/208723856-95126914-02a3-4b78-8260-634651837315.png">

There's no way I can add the faceted column menu to it. When I turn that on, it blows the table wider than 2000 pixels:

<img width="1752" alt="Screenshot 2022-12-20 at 10 35 48 AM" src="https://user-images.githubusercontent.com/814813/208723998-598d6737-adf2-4064-8c16-9bc6a6b847b1.png">

That's probably because of this obscenely long disease: `Malignant neoplasm of nasal cavities middle ear and accessory sinuses`.

Let me know how you want to proceed.

**Comment by nutjob4life** [comment]
Per 2022-12-20 staff meeting: temporarily drop Diseases Studied pie chart & column

**Comment by hoodriverheather** [comment]
Looks great!
