### ISSUE TITLE
Paperless pages

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#191]
https://edrn-dev.jpl.nasa.gov/portal/renaissance/about-edrn/mission-and-structure/groups/breast-and-gynecologic-cancers-research-group/

This list of collaborative groups looks good.

Based on the Secure site - the committees/subcommittees and working groups that need pages are:

- Steering Committee (SC)
- Executive Committee (EC)
- Network Consulting Team (NCT) 
- Prioritization Subcommittee
- Technology and Resource Sharing Subcommittee 
- Communication and Workshop Subcommittee 
- Collaboration and Publication Subcommittee
- Data Sharing and Informatics Subcommittee 
- Standing Review Group
- Statistical Working Group
- Reference Set Working Group

Can you show the Chair and Co-chair just as names that are clickable? It seems like many people don't have images uploaded and I can't click on the image to see how to contact the chair or co-chair.

Is there a form that can be filled out for new Events? That would allow Royce to enter the Date and time for the call, the zoom link and the agenda and link to the minutes from the previous meeting?

Also, is there a way to group many of the documents under the "Events" section so they have more relevance? Many of these documents are minutes from a call. At a minimum we should group them by date? IDK? Or maybe just do that from this point forward? Does Wagtail have any feature like Plone did for Events?

**Comment by nutjob4life** [comment]
@hoodriverheather thanks for testing all this! 🎉 This is a _big_ issue. Let me break it down into sections.

## What Groups to Include

> Based on the Secure site - the committees/subcommittees and working groups that need pages are:
> […]

I've gone ahead and removed these groups:

- associate-member
- biomarker-developmental-laboratories
- biomarker-reference-laboratories
- clinical-epidemiology-and-validation-center
- jet-propulsion-laboratory
- national-cancer-institute
- data-management-and
- erne-working-group

These all appear in the DMCC's SOAP API which is why they also appeared on the Plone portal. They will no longer appear on the Wagtail portal.

That leaves these groups (and, of course, the organ collaborative groups):

| Committee                                    | ID № |
|:---------------------------------------------|-----:|
| Collaboration and Publication Subcommittee   |    7 | 
| Communication and Workshop Subcommittee      |    6 |
| Data Sharing and Informatics Subcommittee    |    8 |
| Executive Committee                          |    2 |
| Network Consulting Team                      |    3 | 
| Prioritization Subcommittee                  |    4 |
| Reference Set Working Group                  |  N/A |
| Standing Review Group                        |  N/A |
| Statistical Working Group                    |  N/A |
| Steering Committee                           |    1 | 
| Technology and Resource Sharing Subcommittee |    5 |

What makes this entire task particularly difficult is that I'm trying to combine two different sources of information into one. The DMCC provides the chair, co-chair, and members of each group, but refuses to provide descriptions for these groups over the SOAP API. So rather than simply do full RDF ingest or full Wagtail-editable, it's a hybrid. Some data comes from SOAP/RDF. Some comes through-the-web editing (and some comes through the upgrade code I'm writing to go from Portal 6.0.1 → 6.0.2).

The groups listed as "N/A" above do not appear in the DMCC's SOAP API at all, which means they must be fully managed by Wagtail, i.e., we'll _manually_ set the chiar, co-chair, members, description text, and permissions to view the pages. The rest will have all that be automatic—except for the description text, and of course, Committee Events and various documents.

👉 **Note:** On the "secure" site, description text is not provided for the Reference Set Working Group or the Statistical Review Group—nor any of the organ collaborative groups. These groups there appear as "No description available" on Portal 6.0.2.


## Clickable Members

> Can you show the Chair and Co-chair just as names that are clickable? It seems like many people don't have images uploaded and I can't click on the image to see how to contact the chair or co-chair.

Image click works for me 🤷‍♀️ But I've removed the images. (I liked having the silhouette images as it might encourage some members to actually provide a photo. But they're gone 👍)


## Committee Events

> Is there a form that can be filled out for new Events? That would allow Royce to enter the Date and time for the call, the zoom link and the agenda and link to the minutes from the previous meeting?

Yes. I even included timezone support:

1. Log in
2. Click on a group
3. Click on the NIH badge and choose "Add child page"
4. Click "Committee Event"
5. Fill out the form
6. Click "Publish"


## Documents

> Also, is there a way to group many of the documents under the "Events" section so they have more relevance?

That's probably a bug. There should be only _events_ appearing under "Events"; documents should go solely under "Documents". I'm looking around at a few groups and so far I'm not finding any documents under "Events". Where did you see this?

> Does Wagtail have any feature like Plone did for Events?

No, but I created one; see "Committee Events", above.

> Also, is there a way to group many of the documents under the "Events" section so they have more relevance? Many of these documents are minutes from a call.

Plone seems to have lost publication date for a number of these items, which I imagine happened between the Plone 4 → 5 transition. In an effort to make this seem like less of a mess, I've changed the import so that:

-   Items from Plone are now under a page labeled "Archived Documents".
-   Those items are ordered by reverse chronological order—but again, that order may not be useful since publication date is a bit wonky.

Note I've done this only for the organ collaborative groups, which seems to have the most empty'is agenda items.

**Comment by hoodriverheather** [comment]
@nutjob4life looks great!

**Comment by nutjob4life** [comment]
![happy-dance](https://user-images.githubusercontent.com/814813/212504500-9028ff9d-76e8-4d16-878f-f5cf5bf11c07.gif)
