### ISSUE TITLE
On-line reference set application

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#225]
## 🤔 Tell Us About the Feature

Develop on-line application pages for EDRN specimen reference sets - https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/

## 🎇 What Solution You'd Like

- Develop a web form based on this application - 

[EDRN_General_Reference_Set_Application_Form_04_02_2015 (2).docx](https://github.com/EDRN/P5/files/10678804/EDRN_General_Reference_Set_Application_Form_04_02_2015.2.docx)

- For Part II create question with text box for answers to questions I. - V.
- Once application is submitted notify DMCC, NCI and reference set working group mailing address.
- Create a "review" form to allow review group to view a summary of the application, review and approve or not approve (yes, no).

## Additional Requirements

The following requirements arose during the Bio-informatics Systems Planning Meeting 2023-03-09:

- [x] Enable the selection of multiple references sets per single application (unlike the current paper forms)
- [x] Instead of a text box for "Scientific Proposal", allow for an uploaded file.
- [x] Send email upon successful submission to `edrndmcc@fredhutch.org`
- [x] Use the new application (which starts on page 3 of the following document)

[EDRN Standard Specimen Reference Set Guidelines-Blinding Policy.pdf](https://github.com/EDRN/P5/files/10936477/EDRN.Standard.Specimen.Reference.Set.Guidelines-Blinding.Policy.pdf)

## 〽️ Alternative Ideas
Do not include a way to review and approve via the on-line forms for this version?

**Comment by nutjob4life** [comment]
@hoodriverheather's notes:

From my notes from our call in December (please let me know if I got any of this incorrect):

- JPL to create an online application
- once application is submitted notify the DMCC and NCI.
- Is the actual review going to be on-line for this version or the next version? _Preferrable this version so in bullet №2 also include the reference set working group mailing address_
- do all specimen reference sets use the same application? It looked like a few have a specific app.  _Right now some use a different application but in this process, I propose that they all use the same common application_
- How should the form handle Part II? Is this a word doc with the header and the footer they would complete and upload with the submission of the form? _I would envision it being one big text box where they type in the answers to I. – V._
- I attached a screenshot of the specimen ref set page that is currently at NCI for release. We changed the yes/no to check marks, but all of this will be editable. Is the Image Files Available? Used to indicate if there are images such as BRSI images available in LabCAS? _I like the check marks.  Image files avail? Does mean that DICOM images are available at JPL_

**Comment by nutjob4life** [comment]
@hoodriverheather I have a prototype here:

https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/

-   The form is currently open to the public but lacks a CAPTCHA. If we make it private to logged-in users we can drop the CAPTCHA and also put in default values. Right now it only defaults your name.
-   The [original form](https://edrn.nci.nih.gov/documents/5/EDRN_General_Reference_Set_Application_Form_04_02_2015.docx) references "eCAS" so this form does too, but shouldn't that be LabCAS?

Right now it just packages up all the answers and email them, and for now it only emails to you and me.

**Comment by hoodriverheather** [comment]
@nutjob4life Looking good. I have a few edits that I made on screenshots. See below.
Also, is there a way to add section headers? It might be nice or maybe too much??
<img width="1270" alt="Screenshot 2023-03-07 at 2 30 13 PM" src="https://user-images.githubusercontent.com/58526347/223573373-c3504f19-0c47-4dee-8206-4fc8a120204a.png">
<img width="1036" alt="Screenshot 2023-03-07 at 2 34 06 PM" src="https://user-images.githubusercontent.com/58526347/223573415-e15e1be9-1b04-40ce-ae59-9dc98cf9d487.png">
<img width="1013" alt="Screenshot 2023-03-07 at 2 46 38 PM" src="https://user-images.githubusercontent.com/58526347/223573426-3250b95b-3be7-406e-a90a-cd88d22992fb.png">

**Comment by hoodriverheather** [comment]
@nutjob4life 
What Happens Next message to the suggested edit in the screenshot? I just don't want the submitter to think the DMCC is reviewing their application, so i took text from the form.
<img width="1081" alt="Screenshot 2023-03-07 at 3 01 53 PM" src="https://user-images.githubusercontent.com/58526347/223574889-b8ec336c-d134-4810-99c2-d2957b3132cb.png">

I know Jackie will be updating this form, so if any of these updates are time consuming we could just hold off and ask her for edits first.

**Comment by nutjob4life** [comment]
@hoodriverheather take a look at https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/ for the latest updates based on your feedback:

-   There's a CAPTCHA
-   Formatting changes
    -   There are now section headers (Scientific Proposal, Affirmations)
    -   The proposal advice text appears before the proposal entry box
-   I haven't touched separate "Your Name" and "Investigator" fields pending feedback from DMCC
-   Added "Collaborative Group Oversight" over the collaborative group checkboxes
    -   Left "Select all that apply" for now pending feedback from DMCC
-   Added "Specimen Type" radiobuttons and "other" blank; still need to confirm if this is select-one or select-many with DMCC
-   A radiobutton to indicate funding that enables/disables other boxes are not possible at this time
    -   So for now I've left the box that lets people explain their funding in prose
    -   Although another option is to provide the various blanks and say "Fill in all that apply"
        -   Let me know if you want to see how that looks
-   I altered the text on the landing page as you suggested
-   I reorganized some of the fields to be next to each other instead of being strictly linear, top-to-bottom

Let me know if there are any other changes needed before the meeting on 3-9.

FYI, this seems to be "challenge logarithmic curve" when doing forms in Wagtail (and its underlying application server, Django):

1. 👶 Trivial: design a form with basic controls that sends an email, through-the-web, no code needed
2. 💪 Easy: a form consisting of a series of linear fields of beyond-the-basics data types—may even have dynamic data choices—that sends email
3. 😅 Intermediate: a form consisting of linear fields that post-processes the data before sending email or does something other than email (this where is the metadata collection form is because it has to generate the `.cfg` file format)
4. 🥵 Difficult: a form that requires special page layout (this is where the reference set application form is now)
5. 🛑 Impossible: inter-dependent field logic: where choices made in one field affect what can be entered into others

Of course, I'm still a newbie when it comes to these technologies. Others out there may have a much better handle on these.

Moving the "Scientific Proposal" preamble text to the middle of the form and adding section headers is what turned the reference set application from level 3 to level 4.

**Comment by hoodriverheather** [comment]
@nutjob4life this is really looking great! Suggested update below to remove **Proposal** header and sentence below (see screenshot).
<img width="1013" alt="Screenshot 2023-03-08 at 1 22 34 PM" src="https://user-images.githubusercontent.com/58526347/223855466-7a3fd126-3914-4b6f-93cb-93cb58f73f0c.png">

I think the section on funding in the word form is just asking for specific items to be checked and data entered. No prose entry. I could be wrong, but when I try to fill that form out in word the "How will testing the reference set(s) be funded?" seems to just be a label. Would you mind making the updates suggested above for the funding section?

The same seems to be the case with the IRB section. "Do you have IRB approval to work with the requested samples?" is a label. I think it's OK to leave that for now.

Thanks for the explanation of the levels for the form development - very helpful!

Thanks!

**Comment by nutjob4life** [comment]
@hoodriverheather wrote:

> Would you mind making the updates suggested above for the funding section?

I would if I could. But like I said, I can't do the funding the way you want above in your [screen shot with red text](https://user-images.githubusercontent.com/58526347/223573426-3250b95b-3be7-406e-a90a-cd88d22992fb.png). There's no way to link one set of controls to other sets fields.

> "A radiobutton to indicate funding that enables/disables other boxes are not possible at this time."
> —Me, [above](https://github.com/EDRN/P5/issues/225#issuecomment-1460849380)

That's why I left a large open box. I _know_ they're not supposed to enter a bunch of prose. But that's the trade-off 🫤 That's why the text below that box says:

> If there is a current NIH-funded grant, enter the grant №, annual direct costs, and funding period. If there is other sponsorship, provide a statement of committment from the sponsoring agency, company, or foundation. If there is some other funding, please specify.

There's no way in Wagtail forms to see if a user checks a box "Current NIH-funded grant" to then enable fields for "Grant number", "Annual Direct Costs", and "Funding Period"—and to validate that "If current NIH-funded grant is checked, ensure values or filled in for these other fields. Or if the user checks "Other" to then turn on a "Specify" box. Etc.

Besides, aren't you supposed to print out the Word forms and fill them in with a pen? It wouldn't matter what parts of the Word document are editable and which aren't, right 🤔

**Comment by nutjob4life** [comment]
@hoodriverheather hang on, I thought of another possible trade-off. There'll be zero validation but it could give separate boxes.

Hang tight.

**Comment by nutjob4life** [comment]
@hoodriverheather  okay try https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/ now.

**Comment by hoodriverheather** [comment]
@nutjob4life Perfecto!! I was going to say, they don't have to be linked, but at least they would have a spot to enter something :)

**Comment by nutjob4life** [comment]
Whew!! 😅

**Comment by nutjob4life** [comment]
The following ref set pages now use the online form:

- Breast Cancer Reference Sets
- Colon Cancer
- Liver (Hepatocellular Carcinoma)
- Lung Cancer
- Pancreatic
- Prostate

Ignore the "(PDF)" that still appears on these pages; those will disappear after tomorrow's (3-11) production database refresh.

I did not link the following ref set pages to the online form because they each used a custom Word doc different from the standard EDRN ref set app form:

- Benign Breast Disease
- BRSCW Ovarian & Breast Cancer

**Comment by hoodriverheather** [comment]
@nutjob4life This is looking great. I think the Specimen Type field also needs to allow select all that apply. I'm not sure if minimum volume needs to change. UGH! I wonder if the volume needs to refer to the specimen type.

**Comment by nutjob4life** [comment]
@hoodriverheather okay, Specimen Type is now checkboxes and min volume is now a text area. [Check it out](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/specimen-set-request-form/).

**Comment by nutjob4life** [comment]
@hoodriverheather to QC this, visit the [Specimen Reference Sets page](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/specimen-reference-sets/) and try one of the links such as "Colon cancer".

- [ ] Ensure you're taken to a page that includes a link `Application Form for EDRN Reference Sets` without `(PDF)` next to it.
- [ ] Ensure the link takes you to an online form
- [ ] Ensure the form has the expected fields and you can fill it out
- [ ] Ensure that after submitting it you get an email with the filled-in data
- [ ] Ensure the email has an attachment consisting of the uploaded scientific proposal file

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great!!
