### ISSUE TITLE
Reference Group Details

### ISSUE THREAD

**Issue by askarlupka** [EDRN/P5#324]
# ✋ Hold it!

Before you submit this request, remember that P5 is a _content management system_. Why not [try doing it yourself](https://edrn.nci.nih.gov/admin)?

## 📕 Summary

The reference set working group description page needs to be updated to reflect current roles and membership (https://edrn.nci.nih.gov/about-edrn/groups/reference-set-working-group/)

- ☑️ replacing existing content

## 🔍 Details

I think the other subcommittee information (example: https://edrn.nci.nih.gov/about-edrn/groups/data-sharing-and-informatics-subcommittee/) may be pulling from the DMCC, so it may need to be updated

**Comment by nutjob4life** [comment]
Hi @askarlupka! Thanks for letting me know about this.

While the DMCC does provide data for several of the committees, working groups, and collaborative groups, sadly the Reference Set Working Group is not one of them.

We can manually update the group at this time, however if turnover in the group is high, it could go out-of-date quickly. Do you or does @hoodriverheather know what the turnover is in the Reference Set Working Group?

A _preferred solution_ would be to ask the DMCC to include the Reference Set Working Group in the [Committees API](https://www.compass.fhcrc.org/edrn_ws/ws_newcompass.asmx?op=Committees) they provide to us. Then it'd be trivial to make it a DMCC-driven group, and it would update automatically. No code change necessary! I would just flip a virtual switch.

Meanwhile I'll assign this to @hoodriverheather for next steps.

**Comment by hoodriverheather** [comment]
@nutjob4life This is now added to the Committees API coming from the DMCC. Should show up as updated tomorrow :)

**Comment by nutjob4life** [comment]
@hoodriverheather I did a manual RDF ingest and "tada" 🎉 the Reference Set Working Group is now there:

https://edrn.nci.nih.gov/about-edrn/groups/reference-set-working-group/

**Comment by hoodriverheather** [comment]
@nutjob4life A few discrepancies I found when comparing to the DMCC Secure Site:
Executive Committee lists members on Portal, but not on Secure Site
Network Consulting Committee lists chair, but on Secure Site also lists members - Are we allowed to show this at all (i'm logged in as a Super User)

**Comment by nutjob4life** [comment]
> Executive Committee lists members on Portal, but not on Secure Site

The SOAP API gives a chair, co-chair, and 11 members for the Executive Committee. I'd recommend following up with the DMCC as to why the SOAP API gives people while they don't show any on their own "secure" site.

> Network Consulting Committee lists chair, but on Secure Site also lists members

The SOAP API for commmittees shows a chair and 5 members for the Network Consulting Team:

| Person ID | Name                     | Site ID |
|----------:|:-------------------------|--------:|
| 4326      | Polyak, Kornelia (Nelly) | 928     |
| 4327      | Johnson, Bruce           | 929     |
| 4328      | Olopade, Funmi           | 930     |
| 4329      | Lidgard, Graham          | 931     |
| 4330      | Philip, Reena            | 932     |

However, the SOAP API for sites gives no information about sites 928, 929, 930, 931, or 932. In the portal, we have to associate people with sites. Since none of these sites exist, the portal cannot create the people, so the Network Consulting Team shows no members.

> Are we allowed to show this at all (i'm logged in as a Super User)

That's a policy question that I can't answer. Sorry! 🙇

**Comment by hoodriverheather** [comment]
@nutjob4life What LDAP groups are allowed to view the Network Consulting Committee page and the Executive Comm page?

**Comment by nutjob4life** [comment]
@hoodriverheather the following

- Executive Committee: Portal Content Custodian, Executive Committee
- Network Consulting Team: Srivastava National Cancer Institute, Portal Content Custodian, Feng Fred Hutchinson Cancer Center, Steering Committee, Super User, Feng Fred Hutchinson Cancer Research Center

Note that there is an [older Network Consulting Team page](https://edrn.nci.nih.gov/network-consulting-team/) imported from the early Plone days. It has the same LDAP groups as the one above under About EDRN → Committees and Collaborative Groups.

(FYI, to view the groups allowed access to any page in the portal, edit that page, click the ℹ️ icon at the top, and click Change privacy. Scroll through the list to see ☑️ by LDAP groups that have access.)

**Comment by nutjob4life** [comment]
@hoodriverheather I'm going to re-focus this issue back onto the Reference Set Working Group so we can call this done for 6.10—which is indeed the case!

As for the Executive Committee and Networking Consulting Team, those issues won't be resolved by code freeze date, so I'll create a separate issue for that.

**Comment by hoodriverheather** [comment]
👍
