### ISSUE TITLE
Combined Site+PI field on Collection and Dataset Metadata Forms

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#334]
@nutjob4life please update the following on the Data Collection Form https://edrn.nci.nih.gov/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/

Easy update:
Add dbGAP as an option for the Reference URL Description.

Question:
Would it be difficult to allow the user to select the LeadPI and that would show/select for them the corresponding Institution? 

Currently the Institution list is really difficult to select from. The names of institutions are entered inconsistently and don't show up on the list grouped together. The list only shows institution and site id, so it's not intuitive to someone selected which site to pick :)

If that's difficult, we can brainstorm other options.
Thanks!
Heather

**Comment by nutjob4life** [comment]
@hoodriverheather adding dbGAP is easy enough; I added it to the [collection form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and the [dataset form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/). Please take a look and confirm.

As you've surmised, yes, the form handling support is on the basic side, so having one field dependent on another is a bit tricky.

However, it hit me that in EDRN, the "funded site" is both the PI and the site, so why treat them separately? As a prototype, take a look at the [collection form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/metadata-collection-form/) and note that I've combined the two fields into one. 

And to make things clearer, I've also included the site role (BCC, BDL, etc.) so you know which is which—in addition to the site ID. What do you think?

The list is long, since it includes all CVCs, BCCs, BDLs, BRLs, plus the DMCC, NCI, and _all_ associate members (A, B, and C). If we could leave out the associate members (or even a subset of them), it'd be helpful! Thoughts?

**Comment by hoodriverheather** [comment]
This is great!Thanks!

**Comment by nutjob4life** [comment]
Hi @hoodriverheather, I added the combined PI+site to the [dataset form](https://edrn-dev.jpl.nasa.gov/portal/renaissance/data-and-resources/cde/labcas-metadata-and-common-data-elements/dataset-metadata-form/) as well.  Could you take a peek and confirm it's working as intended there too?
