### ISSUE TITLE
Added link to Nature Pub on FAIR

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#356]
@nutjob4life I added a link to the Nature publication on FAIR under the Data Sharing Policies - https://edrn.nci.nih.gov/data-and-resources/data-sharing-policies/

I would also like this link on the LabCAS Cancer Biomarker Data Commons page under the Sharing Data link. Which currently links to - 
https://edrn.nci.nih.gov/about-edrn/groups/data-sharing-and-informatics-subcommittee/edrn-external-data-sharing-and-reuse-policy-funding-cycle-v/

What's the best way to have a Data Sharing page with both the policy and the FAIR article linked? Should there just be one page where both of these links live and we point to that page? What's the best way to do this?

**Comment by nutjob4life** [comment]
> I added a link to the Nature publication on FAIR under the Data Sharing Policies

Nice! Looks great!

> I would also like this link on the LabCAS Cancer Biomarker Data Commons page under the Sharing Data link

Oh, okay, so the link [currently on this page](https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/)

> Should there just be one page where both of these links live and we point to that page? 

That does mean if we ever need to update the link, then it only has to be done in one place, so that sounds like the best way.

I've modified [the LabCAS page](https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/) so that "Sharing Data" now points to [your recently updated page](https://edrn.nci.nih.gov/data-and-resources/data-sharing-policies/).

[View it live](https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/).

**Comment by hoodriverheather** [comment]
@nutjob4life Thanks!
