### ISSUE TITLE
Add another icon to this list - Sign up for a LabCAS Account

### ISSUE THREAD

**Issue by hoodriverheather** [EDRN/P5#361]
@nutjob4life Please update the LabCAS Documentation on the EDRN Portal
https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/

Please add another icon - Sign up for a LabCAS Account - https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/sign-up-for-a-labcas-account/

<img width="720" alt="Screenshot 2024-07-03 at 10 40 51 AM" src="https://github.com/EDRN/P5/assets/58526347/c05a2e10-e8f9-4405-85dc-4d79aee67f44">

**Comment by nutjob4life** [comment]
Blocked by:

- [ ] [EDRN/biokey#10](https://github.com/EDRN/biokey/issues/10) since BioKey must be live and open to the public
- [ ] `cn=Public Data,dc=edrn,dc=jpl,dc=nasa,dc=gov` added to `OwnerPrincipal` for files in public collections

@hoodriverheather I see [this issue](https://github.com/EDRN/EDRN-metadata/issues/105) for adding `cn=Public Data,…` to `labacs-dev`. Is there a corresponding issue for `edrn-labcas`? [If not … 😉](https://github.com/EDRN/EDRN-metadata/issues/new)

**Comment by nutjob4life** [comment]
Note to self:  icons used were from [https://pixabay.com/users/io-images-1096650/](this page)

**Comment by nutjob4life** [comment]
[Live now](https://edrn.nci.nih.gov/data-and-resources/informatics/labcas-cancer-biomarker-data-commons/)

If this looks okay, please go ahead and close this issue. If not, assign back to me and let me know what other changes you'd like

**Comment by hoodriverheather** [comment]
@nutjob4life Looks great!
