### ISSUE TITLE
Add protocol ID 427 to BMDB

### ISSUE THREAD

**Issue by mryan4** [EDRN/P5#67]
## 🐛 Describe the Bug

Please add 427, Ovarian Cancer Detection by Uterine Lavage DNA and Serum Proteins: A Phase 2 Biomarker Study, Steve Skates, to BMDB.

(Not really a bug, wasn't sure which to pick - P5 content management?)

**Comment by nutjob4life** [comment]
Hi @mryan4; this issue should be filed in the Biomarker Database, not the EDRN P5 Portal:

https://github.com/EDRN/biomarker-database/issues/new/choose

Thanks!

**Comment by nutjob4life** [comment]
And yes it seems anal retentive @mryan4 but it's also because we automatically generate release notes from closed issues and it would look weird to see (for example):

- Added drop-down menus to portal nav bar
- Fixed portal ingest with protocols
- **Added protocol 427 to BMDB**
- Changed portal colors to match NCI style

in the log! 😂

**Comment by mryan4** [comment]
I must have bookmarked the wrong page. 
Thanks!


Maureen Colbert
Division of Gastroenterology & Hepatology
Department of Medicine
UNC at Chapel Hill





On Sep 1, 2020, at 10:53 AM, Sean Kelly <notifications@github.com> wrote:


Hi @mryan4 <https://github.com/mryan4>; this issue should be filed in the Biomarker Database, not the EDRN P5 Portal:

https://github.com/EDRN/biomarker-database/issues/new/choose <https://github.com/EDRN/biomarker-database/issues/new/choose>
Thanks!
